name = "maintenance-page"
main = "maintenance-worker.js"
compatibility_date = "2023-12-26"

# Configure account ID from environment
account_id = "${CF_ACCOUNT_ID}"
workers_dev = true  # Enable for testing on workers.dev subdomain

# Variables
[vars]
MAINTENANCE_MODE = false

# Production environment
[env.production]
# Routes are configured via environment variables
routes = [
    { pattern = "*.rashlink.eu.org/*", zone_id = "${CF_ZONE_ID}" },
    { pattern = "rashlink.eu.org/*", zone_id = "${CF_ZONE_ID}" }
]

# Development environment
[env.development]
workers_dev = true
vars = { MAINTENANCE_MODE = true }
