version: '3.8'

services:
  gps-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gps-service
    ports:
      - "8110:3000"   # HTTP port
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MAX_MEMORY=512M
      - CORS_ORIGINS=https://*.rashlink.eu.org,http://localhost:3000
      - VIRTUAL_HOST=gpsconnect.rashlink.eu.org
      - ENABLE_HTTPS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gps-network

networks:
  gps-network:
    driver: bridge
